from __future__ import annotations

from typing import Protocol

from core.state.models import (
    ArtifactRecord,
    InterruptRecord,
    NodeState,
    PolicyDecisionRecord,
    RunRecord,
    RunState,
    SideEffectRecord,
    ThreadRecord,
    ThreadState,
)

from .types import StateStoreSnapshot


class StateStore(Protocol):
    def get_thread_record(self, thread_id: str) -> ThreadRecord | None: ...

    def save_thread_record(self, thread_record: ThreadRecord) -> ThreadRecord: ...

    def get_run_record(self, run_id: str) -> RunRecord | None: ...

    def save_run_record(self, run_record: RunRecord) -> RunRecord: ...

    def get_thread_state(self, thread_id: str) -> ThreadState | None: ...

    def save_thread_state(self, thread_state: ThreadState) -> ThreadState: ...

    def get_run_state(self, run_id: str) -> RunState | None: ...

    def save_run_state(self, run_state: RunState) -> RunState: ...

    def get_node_state(self, run_id: str, node_id: str) -> NodeState | None: ...

    def save_node_state(self, node_state: NodeState) -> NodeState: ...

    def list_node_states(self, run_id: str) -> list[NodeState]: ...

    def save_artifact(self, artifact_record: ArtifactRecord) -> ArtifactRecord: ...

    def get_artifact(self, artifact_id: str) -> ArtifactRecord | None: ...

    def list_artifacts(self, run_id: str) -> list[ArtifactRecord]: ...

    def save_interrupt(self, interrupt_record: InterruptRecord) -> InterruptRecord: ...

    def get_interrupt(self, interrupt_id: str) -> InterruptRecord | None: ...

    def list_interrupts(self, run_id: str) -> list[InterruptRecord]: ...

    def save_policy_decision(
        self, record: PolicyDecisionRecord
    ) -> PolicyDecisionRecord: ...

    def list_policy_decisions(self, run_id: str) -> list[PolicyDecisionRecord]: ...

    def save_side_effect(self, record: SideEffectRecord) -> SideEffectRecord: ...

    def list_side_effects(self, run_id: str) -> list[SideEffectRecord]: ...

    def build_snapshot(self, run_id: str) -> StateStoreSnapshot: ...

