from __future__ import annotations

from copy import deepcopy

from core.state.models import SideEffectKind
from core.tools import ToolApprovalMode, ToolDescriptor, ToolTransportKind

from .constants import OPERATION_TOOL_REFS


_OPERATION_TOOL_DESCRIPTORS = [
    ToolDescriptor(
        tool_ref=OPERATION_TOOL_REFS["list_dir"],
        name="Workspace Directory List",
        description="List files and directories within the allowed workspace root.",
        transport_kind=ToolTransportKind.LOCAL_FUNCTION,
        input_schema={"type": "object", "properties": {"path": {"type": "string"}}},
        output_schema={"type": "object", "properties": {"path": {"type": "string"}, "items": {"type": "array"}}},
        side_effect_kind=SideEffectKind.READ_ONLY,
        approval_mode=ToolApprovalMode.NONE,
        provider_ref="shared.local_workspace",
        operation_ref="list_dir",
        timeout_ms=2_000,
        is_idempotent=True,
        tags=["shared", "filesystem", "directory"],
        metadata={"domain": "shared", "tool_kind": "filesystem"},
    ),
    ToolDescriptor(
        tool_ref=OPERATION_TOOL_REFS["list_files"],
        name="Workspace File List",
        description="List files under a directory within the allowed workspace root, with optional recursion and filtering.",
        transport_kind=ToolTransportKind.LOCAL_FUNCTION,
        input_schema={
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "recursive": {"type": "boolean"},
                "limit": {"type": "integer"},
                "extensions": {"type": "array", "items": {"type": "string"}},
            },
        },
        output_schema={"type": "object", "properties": {"path": {"type": "string"}, "items": {"type": "array"}}},
        side_effect_kind=SideEffectKind.READ_ONLY,
        approval_mode=ToolApprovalMode.NONE,
        provider_ref="shared.local_workspace",
        operation_ref="list_files",
        timeout_ms=3_000,
        is_idempotent=True,
        tags=["shared", "filesystem", "list"],
        metadata={"domain": "shared", "tool_kind": "filesystem"},
    ),
    ToolDescriptor(
        tool_ref=OPERATION_TOOL_REFS["read_file"],
        name="Workspace File Read",
        description="Read a text file from the allowed workspace root.",
        transport_kind=ToolTransportKind.LOCAL_FUNCTION,
        input_schema={"type": "object", "properties": {"path": {"type": "string"}}, "required": ["path"]},
        output_schema={
            "type": "object",
            "properties": {"path": {"type": "string"}, "content": {"type": "string"}, "line_count": {"type": "integer"}},
        },
        side_effect_kind=SideEffectKind.READ_ONLY,
        approval_mode=ToolApprovalMode.NONE,
        provider_ref="shared.local_workspace",
        operation_ref="read_file",
        timeout_ms=2_000,
        is_idempotent=True,
        tags=["shared", "filesystem", "read"],
        metadata={"domain": "shared", "tool_kind": "filesystem"},
    ),
    ToolDescriptor(
        tool_ref=OPERATION_TOOL_REFS["read_file_segment"],
        name="Workspace File Segment Read",
        description="Read a specific line range from a text file within the allowed workspace root.",
        transport_kind=ToolTransportKind.LOCAL_FUNCTION,
        input_schema={
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "start_line": {"type": "integer"},
                "end_line": {"type": "integer"},
            },
            "required": ["path"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "content": {"type": "string"},
                "start_line": {"type": "integer"},
                "end_line": {"type": "integer"},
                "total_line_count": {"type": "integer"},
            },
        },
        side_effect_kind=SideEffectKind.READ_ONLY,
        approval_mode=ToolApprovalMode.NONE,
        provider_ref="shared.local_workspace",
        operation_ref="read_file_segment",
        timeout_ms=2_000,
        is_idempotent=True,
        tags=["shared", "filesystem", "read"],
        metadata={"domain": "shared", "tool_kind": "filesystem"},
    ),
    ToolDescriptor(
        tool_ref=OPERATION_TOOL_REFS["find_in_file"],
        name="Workspace Find In File",
        description="Locate text matches within a single file and return line numbers with previews.",
        transport_kind=ToolTransportKind.LOCAL_FUNCTION,
        input_schema={
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "pattern": {"type": "string"},
                "case_sensitive": {"type": "boolean"},
                "limit": {"type": "integer"},
            },
            "required": ["path", "pattern"],
        },
        output_schema={
            "type": "object",
            "properties": {"path": {"type": "string"}, "pattern": {"type": "string"}, "matches": {"type": "array"}},
        },
        side_effect_kind=SideEffectKind.READ_ONLY,
        approval_mode=ToolApprovalMode.NONE,
        provider_ref="shared.local_workspace",
        operation_ref="find_in_file",
        timeout_ms=2_000,
        is_idempotent=True,
        tags=["shared", "filesystem", "search"],
        metadata={"domain": "shared", "tool_kind": "filesystem"},
    ),
    ToolDescriptor(
        tool_ref=OPERATION_TOOL_REFS["search_files"],
        name="Workspace File Search",
        description="Search file paths and file contents inside the allowed workspace root.",
        transport_kind=ToolTransportKind.LOCAL_FUNCTION,
        input_schema={
            "type": "object",
            "properties": {
                "pattern": {"type": "string"},
                "path": {"type": "string"},
                "include_content": {"type": "boolean"},
                "limit": {"type": "integer"},
            },
            "required": ["pattern"],
        },
        output_schema={
            "type": "object",
            "properties": {"pattern": {"type": "string"}, "matches": {"type": "array"}, "searched_root": {"type": "string"}},
        },
        side_effect_kind=SideEffectKind.READ_ONLY,
        approval_mode=ToolApprovalMode.NONE,
        provider_ref="shared.local_workspace",
        operation_ref="search_files",
        timeout_ms=5_000,
        is_idempotent=True,
        tags=["shared", "filesystem", "search"],
        metadata={"domain": "shared", "tool_kind": "filesystem"},
    ),
    ToolDescriptor(
        tool_ref=OPERATION_TOOL_REFS["ripgrep_search"],
        name="Workspace Ripgrep Search",
        description="Search file paths and text content with ripgrep-style filters, limits, and previews.",
        transport_kind=ToolTransportKind.LOCAL_FUNCTION,
        input_schema={
            "type": "object",
            "properties": {
                "pattern": {"type": "string"},
                "path": {"type": "string"},
                "glob": {"type": "string"},
                "case_sensitive": {"type": "boolean"},
                "limit": {"type": "integer"},
                "max_file_size_kb": {"type": "integer"},
            },
            "required": ["pattern"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "pattern": {"type": "string"},
                "matches": {"type": "array"},
                "searched_root": {"type": "string"},
                "truncated": {"type": "boolean"},
            },
        },
        side_effect_kind=SideEffectKind.READ_ONLY,
        approval_mode=ToolApprovalMode.NONE,
        provider_ref="shared.local_workspace",
        operation_ref="ripgrep_search",
        timeout_ms=5_000,
        is_idempotent=True,
        tags=["shared", "filesystem", "search", "rg"],
        metadata={"domain": "shared", "tool_kind": "filesystem"},
    ),
    ToolDescriptor(
        tool_ref=OPERATION_TOOL_REFS["write_file"],
        name="Workspace File Write",
        description="Write text content to a file within the allowed workspace root.",
        transport_kind=ToolTransportKind.LOCAL_FUNCTION,
        input_schema={
            "type": "object",
            "properties": {"path": {"type": "string"}, "content": {"type": "string"}},
            "required": ["path", "content"],
        },
        output_schema={"type": "object", "properties": {"path": {"type": "string"}, "bytes_written": {"type": "integer"}}},
        side_effect_kind=SideEffectKind.LOCAL_WRITE,
        approval_mode=ToolApprovalMode.NONE,
        provider_ref="shared.local_workspace",
        operation_ref="write_file",
        timeout_ms=2_000,
        is_idempotent=False,
        tags=["shared", "filesystem", "write"],
        metadata={"domain": "shared", "tool_kind": "filesystem"},
    ),
    ToolDescriptor(
        tool_ref=OPERATION_TOOL_REFS["apply_patch"],
        name="Workspace Apply Patch",
        description="Apply a small structured patch to files within the allowed workspace root.",
        transport_kind=ToolTransportKind.LOCAL_FUNCTION,
        input_schema={
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "patch": {"type": "string"},
            },
            "required": ["path", "patch"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "applied": {"type": "boolean"},
                "change_count": {"type": "integer"},
            },
        },
        side_effect_kind=SideEffectKind.LOCAL_WRITE,
        approval_mode=ToolApprovalMode.NONE,
        provider_ref="shared.local_workspace",
        operation_ref="apply_patch",
        timeout_ms=3_000,
        is_idempotent=False,
        tags=["shared", "filesystem", "write", "patch"],
        metadata={"domain": "shared", "tool_kind": "filesystem"},
    ),
    ToolDescriptor(
        tool_ref=OPERATION_TOOL_REFS["make_dir"],
        name="Workspace Directory Create",
        description="Create a directory within the allowed workspace root.",
        transport_kind=ToolTransportKind.LOCAL_FUNCTION,
        input_schema={"type": "object", "properties": {"path": {"type": "string"}}, "required": ["path"]},
        output_schema={"type": "object", "properties": {"path": {"type": "string"}}},
        side_effect_kind=SideEffectKind.LOCAL_WRITE,
        approval_mode=ToolApprovalMode.NONE,
        provider_ref="shared.local_workspace",
        operation_ref="make_dir",
        timeout_ms=2_000,
        is_idempotent=False,
        tags=["shared", "filesystem", "directory"],
        metadata={"domain": "shared", "tool_kind": "filesystem"},
    ),
    ToolDescriptor(
        tool_ref=OPERATION_TOOL_REFS["delete_file"],
        name="Workspace File Delete",
        description="Delete a file within the allowed workspace root.",
        transport_kind=ToolTransportKind.LOCAL_FUNCTION,
        input_schema={"type": "object", "properties": {"path": {"type": "string"}}, "required": ["path"]},
        output_schema={"type": "object", "properties": {"path": {"type": "string"}, "deleted": {"type": "boolean"}}},
        side_effect_kind=SideEffectKind.LOCAL_WRITE,
        approval_mode=ToolApprovalMode.NONE,
        provider_ref="shared.local_workspace",
        operation_ref="delete_file",
        timeout_ms=2_000,
        is_idempotent=False,
        tags=["shared", "filesystem", "delete"],
        metadata={"domain": "shared", "tool_kind": "filesystem"},
    ),
    ToolDescriptor(
        tool_ref=OPERATION_TOOL_REFS["move_file"],
        name="Workspace File Move",
        description="Move or rename a file within the allowed workspace root.",
        transport_kind=ToolTransportKind.LOCAL_FUNCTION,
        input_schema={
            "type": "object",
            "properties": {"source_path": {"type": "string"}, "destination_path": {"type": "string"}},
            "required": ["source_path", "destination_path"],
        },
        output_schema={
            "type": "object",
            "properties": {"source_path": {"type": "string"}, "destination_path": {"type": "string"}},
        },
        side_effect_kind=SideEffectKind.LOCAL_WRITE,
        approval_mode=ToolApprovalMode.NONE,
        provider_ref="shared.local_workspace",
        operation_ref="move_file",
        timeout_ms=2_000,
        is_idempotent=False,
        tags=["shared", "filesystem", "move"],
        metadata={"domain": "shared", "tool_kind": "filesystem"},
    ),
    ToolDescriptor(
        tool_ref=OPERATION_TOOL_REFS["shell_run"],
        name="Workspace Shell Run",
        description="Run a shell command within the allowed workspace root and return stdout, stderr, and exit status.",
        transport_kind=ToolTransportKind.LOCAL_FUNCTION,
        input_schema={
            "type": "object",
            "properties": {"command": {"type": "string"}, "workdir": {"type": "string"}, "timeout_ms": {"type": "integer"}},
            "required": ["command"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "command": {"type": "string"},
                "workdir": {"type": "string"},
                "stdout": {"type": "string"},
                "stderr": {"type": "string"},
                "exit_code": {"type": "integer"},
            },
        },
        side_effect_kind=SideEffectKind.LOCAL_WRITE,
        approval_mode=ToolApprovalMode.NONE,
        provider_ref="shared.local_workspace",
        operation_ref="shell_run",
        timeout_ms=15_000,
        is_idempotent=False,
        tags=["shared", "shell", "workspace"],
        metadata={"domain": "shared", "tool_kind": "shell"},
    ),
    ToolDescriptor(
        tool_ref=OPERATION_TOOL_REFS["git_status"],
        name="Git Status",
        description="Inspect git status within the allowed workspace root.",
        transport_kind=ToolTransportKind.LOCAL_FUNCTION,
        input_schema={"type": "object", "properties": {"path": {"type": "string"}}},
        output_schema={
            "type": "object",
            "properties": {"path": {"type": "string"}, "branch": {"type": "string"}, "status_lines": {"type": "array"}},
        },
        side_effect_kind=SideEffectKind.READ_ONLY,
        approval_mode=ToolApprovalMode.NONE,
        provider_ref="shared.local_workspace",
        operation_ref="git_status",
        timeout_ms=5_000,
        is_idempotent=True,
        tags=["shared", "git", "read"],
        metadata={"domain": "shared", "tool_kind": "git"},
    ),
    ToolDescriptor(
        tool_ref=OPERATION_TOOL_REFS["git_diff"],
        name="Git Diff",
        description="Read git diff within the allowed workspace root.",
        transport_kind=ToolTransportKind.LOCAL_FUNCTION,
        input_schema={"type": "object", "properties": {"path": {"type": "string"}, "target": {"type": "string"}}},
        output_schema={"type": "object", "properties": {"path": {"type": "string"}, "target": {"type": "string"}, "diff": {"type": "string"}}},
        side_effect_kind=SideEffectKind.READ_ONLY,
        approval_mode=ToolApprovalMode.NONE,
        provider_ref="shared.local_workspace",
        operation_ref="git_diff",
        timeout_ms=5_000,
        is_idempotent=True,
        tags=["shared", "git", "read"],
        metadata={"domain": "shared", "tool_kind": "git"},
    ),
]


def get_operation_tool_descriptors() -> list[ToolDescriptor]:
    return [deepcopy(descriptor) for descriptor in _OPERATION_TOOL_DESCRIPTORS]
